package ir.aut.logmonitor.alert;

import jakarta.persistence.*;

import java.time.LocalDateTime;

/**
 * Represents a single alert generated by the Rule Evaluator when a rule's
 * condition is triggered. Persisted to PostgreSQL.
 */
@Entity
@Table(name = "alerts")
public class Alert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Name of the rule that triggered this alert (e.g. "error-log-rule"). */
    @Column(nullable = false)
    private String ruleName;

    /** Name of the component (system) this alert was generated for. */
    @Column(nullable = false)
    private String componentName;

    /** Human-readable description of what triggered the alert. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String description;

    /** Exact date/time the alert was generated. */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    // Required no-arg constructor for JPA
    protected Alert() {
    }

    public Alert(String ruleName, String componentName, String description, LocalDateTime createdAt) {
        this.ruleName = ruleName;
        this.componentName = componentName;
        this.description = description;
        this.createdAt = createdAt;
    }

    public Long getId() {
        return id;
    }

    public String getRuleName() {
        return ruleName;
    }

    public String getComponentName() {
        return componentName;
    }

    public String getDescription() {
        return description;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}